const response = (shape) => JSON.stringify(shape, null, 2);

function api(id, name, description, category, baseUrl, authentication, reference, endpoint, testable = false, tags = []) {
  const [endpointName, method, path, parameters = "", exampleResponse = { ok: true }] = endpoint;
  return {
    id, name, description, desc: description, category, baseUrl, authentication, auth: authentication, reference, testable,
    tags: [category, ...tags], keywords: `${name} ${description} ${category}`.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean),
    endpoints: [{ name: endpointName, method, path, parameters, body: "", exampleRequest: `${method} ${baseUrl}${path}`, example: response(exampleResponse) }]
  };
}

// Each entry links to the provider's own documentation. Keyless examples are marked
// testable; credentialed services remain documented without asking users for secrets.
export const apiCatalog = [
  // Testing
  api("jsonplaceholder", "JSONPlaceholder", "Fake REST resources for prototypes and request testing.", "Testing", "https://jsonplaceholder.typicode.com", "None", "https://jsonplaceholder.typicode.com/guide/", ["Get a post", "GET", "/posts/1", "", { id: 1, title: "..." }], true, ["REST", "Mock"]),
  api("httpbin", "httpbin", "HTTP request and response inspection service.", "Testing", "https://httpbin.org", "None", "https://httpbin.org/", ["Inspect a GET", "GET", "/get", "sample=apihub", { args: { sample: "apihub" } }], true, ["HTTP"]),
  api("postman-echo", "Postman Echo", "Echo service for testing request methods and headers.", "Testing", "https://postman-echo.com", "None", "https://www.postman.com/postman/workspace/postman-public-workspace/documentation/12959542-4fa61a3c-6c8f-4c67-bf47-16c27b1e7db4", ["Echo a GET", "GET", "/get", "foo=bar", { args: { foo: "bar" } }], true, ["HTTP"]),
  api("reqres", "ReqRes", "Hosted sample users and resources for frontend testing.", "Testing", "https://reqres.in", "API key required for requests", "https://reqres.in/", ["List users", "GET", "/api/users", "page=2", { page: 2, data: [] }], false, ["Mock"]),
  api("dummyjson", "DummyJSON", "Sample products, users, carts and posts.", "Testing", "https://dummyjson.com", "None", "https://dummyjson.com/docs", ["Get a product", "GET", "/products/1", "", { id: 1, title: "iPhone 9" }], true, ["Mock"]),
  api("beeceptor", "Beeceptor", "Configurable mock REST endpoints for development.", "Testing", "https://api.beeceptor.com", "Account or custom endpoint required", "https://beeceptor.com/docs/", ["List endpoints", "GET", "/api/endpoints", "", { endpoints: [] }], false, ["Mock"]),

  // Public
  api("dog-ceo", "Dog CEO", "Dog breed images and breed lists.", "Public", "https://dog.ceo/api", "None", "https://dog.ceo/dog-api/documentation/", ["Random dog image", "GET", "/breeds/image/random", "", { message: "https://images.dog.ceo/...", status: "success" }], true, ["Animals"]),
  api("cat-facts", "Cat Facts", "Random cat facts in JSON.", "Public", "https://catfact.ninja", "None", "https://catfact.ninja/", ["Get a fact", "GET", "/fact", "", { fact: "Cats ...", length: 42 }], true, ["Animals"]),
  api("agify", "Agify", "Estimates age from a first name.", "Public", "https://api.agify.io", "None", "https://agify.io/", ["Predict age", "GET", "/", "name=michael", { name: "michael", age: 69, count: 0 }], true, ["Data"]),
  api("genderize", "Genderize", "Predicts likely gender from a first name.", "Public", "https://api.genderize.io", "None", "https://genderize.io/", ["Predict gender", "GET", "/", "name=alex", { name: "alex", gender: "male", probability: 0.5 }], true, ["Data"]),
  api("nationalize", "Nationalize", "Predicts nationalities associated with a first name.", "Public", "https://api.nationalize.io", "None", "https://nationalize.io/", ["Predict nationality", "GET", "/", "name=maria", { name: "maria", country: [] }], true, ["Data"]),
  api("bored", "Bored API", "Ideas for activities when you need inspiration.", "Public", "https://bored-api.appbrewery.com", "None", "https://bored-api.appbrewery.com/", ["Find activity", "GET", "/random", "", { activity: "Learn a new skill" }], true, ["Fun"]),

  // Weather
  api("open-meteo", "Open-Meteo", "Global weather forecasts and current conditions.", "Weather", "https://api.open-meteo.com/v1", "None", "https://open-meteo.com/en/docs", ["Forecast", "GET", "/forecast", "latitude=28.6139\nlongitude=77.2090\ncurrent=temperature_2m", { current: { temperature_2m: 0 } }], true, ["Forecast"]),
  api("met-no", "MET Norway Locationforecast", "Weather forecasts from Norway's Meteorological Institute.", "Weather", "https://api.met.no/weatherapi/locationforecast/2.0", "User-Agent identification required", "https://api.met.no/weatherapi/locationforecast/2.0/documentation", ["Compact forecast", "GET", "/compact", "lat=59.91\nlon=10.75", { properties: { timeseries: [] } }], false, ["Forecast"]),
  api("weatherapi", "WeatherAPI.com", "Current weather, forecasts and astronomy.", "Weather", "https://api.weatherapi.com/v1", "API key required", "https://www.weatherapi.com/docs/", ["Current conditions", "GET", "/current.json", "q=London", { location: {}, current: {} }], false, ["Forecast"]),
  api("openweather", "OpenWeather", "Weather, forecast and geocoding services.", "Weather", "https://api.openweathermap.org/data/2.5", "API key required", "https://openweathermap.org/api", ["Current weather", "GET", "/weather", "q=Delhi", { weather: [], main: {} }], false, ["Forecast"]),
  api("tomorrow", "Tomorrow.io", "Weather forecasts and timelines.", "Weather", "https://api.tomorrow.io/v4", "API key required", "https://docs.tomorrow.io/", ["Weather forecast", "GET", "/weather/forecast", "location=Delhi", { timelines: {} }], false, ["Forecast"]),
  api("visual-crossing", "Visual Crossing Weather", "Historical and forecast weather data.", "Weather", "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services", "API key required", "https://www.visualcrossing.com/resources/documentation/weather-api/", ["Timeline weather", "GET", "/timeline/London", "", { days: [] }], false, ["Forecast"]),

  // Countries
  api("rest-countries", "REST Countries", "Countries, capitals, flags, regions and populations.", "Countries", "https://restcountries.com/v3.1", "None", "https://restcountries.com/", ["Find a country", "GET", "/name/india", "", [{ name: { common: "India" } }]], true, ["Geography"]),
  api("world-bank", "World Bank Indicators", "Global development indicators and country data.", "Countries", "https://api.worldbank.org/v2", "None", "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation", ["Country data", "GET", "/country/IND", "format=json", [{ id: "IND", name: "India" }]], true, ["Economics"]),
  api("countriesnow", "CountriesNow", "Country and city data including capitals and populations.", "Countries", "https://countriesnow.space/api/v0.1", "None", "https://countriesnow.space/", ["Countries and capitals", "GET", "/countries/capital", "", { error: false, data: [] }], true, ["Geography"]),
  api("geonames", "GeoNames", "Geographical names and country information.", "Countries", "http://api.geonames.org", "Username required", "https://www.geonames.org/export/web-services.html", ["Country info", "GET", "/countryInfoJSON", "country=IN", { geonames: [] }], false, ["Geography"]),
  api("nager-date", "Nager.Date", "Public holidays and country metadata.", "Countries", "https://date.nager.at/api/v3", "None", "https://date.nager.at/Api", ["Available countries", "GET", "/AvailableCountries", "", [{ countryCode: "IN", name: "India" }]], true, ["Holidays"]),
  api("ipapi", "ipapi.co", "IP address geolocation and country lookup.", "Countries", "https://ipapi.co", "Rate limits apply", "https://ipapi.co/api/", ["Current IP country", "GET", "/json/", "", { country_name: "..." }], true, ["IP"]),

  // Maps / Location
  api("nominatim", "OpenStreetMap Nominatim", "Geocoding and place search using OpenStreetMap data.", "Maps / Location", "https://nominatim.openstreetmap.org", "User-Agent required by usage policy", "https://nominatim.org/release-docs/latest/api/Overview/", ["Search places", "GET", "/search", "q=New+Delhi\nformat=json", [{ display_name: "New Delhi, India" }]], false, ["Geocoding"]),
  api("bigdatacloud", "BigDataCloud Reverse Geocode", "Reverse geocoding for coordinates.", "Maps / Location", "https://api.bigdatacloud.net/data", "Client key recommended", "https://www.bigdatacloud.com/docs/api/reverse-geocode-client", ["Reverse geocode", "GET", "/reverse-geocode-client", "latitude=28.6139\nlongitude=77.2090\nlocalityLanguage=en", { city: "New Delhi" }], true, ["Geocoding"]),
  api("mapbox", "Mapbox Geocoding", "Forward and reverse geocoding and mapping services.", "Maps / Location", "https://api.mapbox.com/search/geocode/v6", "Access token required", "https://docs.mapbox.com/api/search/geocoding/", ["Forward geocode", "GET", "/forward", "q=Paris", { features: [] }], false, ["Geocoding"]),
  api("google-maps", "Google Maps Platform", "Maps, routes, places and geocoding.", "Maps / Location", "https://maps.googleapis.com/maps/api", "API key and billing required", "https://developers.google.com/maps/documentation", ["Geocode address", "GET", "/geocode/json", "address=New+Delhi", { results: [], status: "OK" }], false, ["Geocoding"]),
  api("here", "HERE Location Services", "Geocoding, routing and maps.", "Maps / Location", "https://geocode.search.hereapi.com/v1", "API key required", "https://developer.here.com/documentation", ["Geocode query", "GET", "/geocode", "q=Berlin", { items: [] }], false, ["Geocoding"]),
  api("opencage", "OpenCage Geocoding", "Worldwide geocoding and reverse geocoding.", "Maps / Location", "https://api.opencagedata.com/geocode/v1", "API key required", "https://opencagedata.com/api", ["Geocode", "GET", "/json", "q=London", { results: [] }], false, ["Geocoding"]),

  // Finance
  api("frankfurter", "Frankfurter", "Foreign-exchange reference rates from central banks.", "Finance", "https://api.frankfurter.dev/v1", "None", "https://frankfurter.dev/", ["Latest rates", "GET", "/latest", "base=USD\nsymbols=INR", { base: "USD", rates: { INR: 0 } }], true, ["FX"]),
  api("exchangerate-host", "ExchangeRate.host", "Currency conversion and exchange-rate data.", "Finance", "https://api.exchangerate.host", "API key required", "https://exchangerate.host/documentation", ["Latest rates", "GET", "/live", "source=USD", { quotes: {} }], false, ["FX"]),
  api("alpha-vantage", "Alpha Vantage", "Stocks, forex, crypto and technical indicators.", "Finance", "https://www.alphavantage.co/query", "API key required", "https://www.alphavantage.co/documentation/", ["Daily stock data", "GET", "/", "function=TIME_SERIES_DAILY\nsymbol=IBM", { "Meta Data": {} }], false, ["Stocks"]),
  api("finnhub", "Finnhub", "Market data, company fundamentals and news.", "Finance", "https://finnhub.io/api/v1", "API token required", "https://finnhub.io/docs/api", ["Quote", "GET", "/quote", "symbol=AAPL", { c: 0, d: 0 }], false, ["Stocks"]),
  api("twelvedata", "Twelve Data", "Financial market and forex time series.", "Finance", "https://api.twelvedata.com", "API key required", "https://twelvedata.com/docs", ["Time series", "GET", "/time_series", "symbol=AAPL\ninterval=1day", { values: [] }], false, ["Stocks"]),
  api("polygon", "Polygon.io", "Stocks, options, forex and crypto market data.", "Finance", "https://api.polygon.io", "API key required", "https://polygon.io/docs", ["Previous close", "GET", "/v2/aggs/ticker/AAPL/prev", "", { results: [] }], false, ["Stocks"]),

  // Crypto
  api("coingecko", "CoinGecko", "Cryptocurrency prices, markets and metadata.", "Crypto", "https://api.coingecko.com/api/v3", "Demo/API key required", "https://docs.coingecko.com/", ["Simple price", "GET", "/simple/price", "ids=bitcoin\nvs_currencies=usd", { bitcoin: { usd: 0 } }], false, ["Markets"]),
  api("coinbase", "Coinbase Exchange", "Public market data for Coinbase Exchange pairs.", "Crypto", "https://api.exchange.coinbase.com", "None for public endpoints", "https://docs.cdp.coinbase.com/exchange/reference/exchangerestapi_getproductticker", ["BTC-USD ticker", "GET", "/products/BTC-USD/ticker", "", { price: "0", product_id: "BTC-USD" }], true, ["Markets"]),
  api("kraken", "Kraken REST API", "Public and private Kraken crypto exchange endpoints.", "Crypto", "https://api.kraken.com/0/public", "None for public endpoints", "https://docs.kraken.com/api/docs/rest-api/get-ticker-information/", ["Ticker", "GET", "/Ticker", "pair=XBTUSD", { error: [], result: {} }], true, ["Markets"]),
  api("binance", "Binance Spot API", "Spot exchange market data and trading endpoints.", "Crypto", "https://api.binance.com/api/v3", "None for public market data", "https://developers.binance.com/docs/binance-spot-api-docs/rest-api/market-data-endpoints", ["Price ticker", "GET", "/ticker/price", "symbol=BTCUSDT", { symbol: "BTCUSDT", price: "0" }], true, ["Markets"]),
  api("coinpaprika", "Coinpaprika", "Crypto assets, markets and exchange data.", "Crypto", "https://api.coinpaprika.com/v1", "None", "https://docs.coinpaprika.com/", ["List coins", "GET", "/coins", "", [{ id: "btc-bitcoin", name: "Bitcoin" }]], true, ["Markets"]),
  api("blockchain-info", "Blockchain.com Charts", "Blockchain statistics and chart data.", "Crypto", "https://api.blockchain.info", "None", "https://www.blockchain.com/explorer/api/charts_api", ["Market price chart", "GET", "/charts/market-price", "timespan=30days\nformat=json", { values: [] }], true, ["Blockchain"]),

  // News
  api("newsapi", "NewsAPI", "Headlines and article search.", "News", "https://newsapi.org/v2", "API key required", "https://newsapi.org/docs", ["Top headlines", "GET", "/top-headlines", "country=us", { articles: [] }], false, ["Articles"]),
  api("guardian", "The Guardian Open Platform", "Guardian content, tags and sections.", "News", "https://content.guardianapis.com", "API key required", "https://open-platform.theguardian.com/documentation/", ["Search content", "GET", "/search", "q=technology", { response: { results: [] } }], false, ["Articles"]),
  api("nyt", "New York Times APIs", "NYT articles, books and popular stories.", "News", "https://api.nytimes.com/svc", "API key required", "https://developer.nytimes.com/docs", ["Most popular", "GET", "/mostpopular/v2/viewed/1.json", "", { results: [] }], false, ["Articles"]),
  api("gnews", "GNews", "International news search and top headlines.", "News", "https://gnews.io/api/v4", "API token required", "https://gnews.io/docs/v4", ["Top headlines", "GET", "/top-headlines", "category=general", { articles: [] }], false, ["Articles"]),
  api("mediastack", "Mediastack", "Live and historical news data.", "News", "https://api.mediastack.com/v1", "Access key required", "https://mediastack.com/documentation", ["Latest news", "GET", "/news", "countries=us", { data: [] }], false, ["Articles"]),
  api("currents", "Currents API", "News search and latest headlines.", "News", "https://api.currentsapi.services/v1", "API key required", "https://currentsapi.services/en/docs/", ["Latest news", "GET", "/latest-news", "language=en", { news: [] }], false, ["Articles"]),

  // Sports
  api("thesportsdb", "TheSportsDB", "Sports leagues, teams, players and events.", "Sports", "https://www.thesportsdb.com/api/v1/json/3", "Free key 3 for sample endpoints", "https://www.thesportsdb.com/api.php", ["Search team", "GET", "/searchteams.php", "t=Arsenal", { teams: [] }], true, ["Teams"]),
  api("football-data", "football-data.org", "Football competitions, teams and matches.", "Sports", "https://api.football-data.org/v4", "API token required", "https://www.football-data.org/documentation/quickstart", ["Premier League", "GET", "/competitions/PL", "", { id: 2021, name: "Premier League" }], false, ["Football"]),
  api("api-football", "API-Football", "Fixtures, standings and statistics for football.", "Sports", "https://v3.football.api-sports.io", "API key required", "https://www.api-football.com/documentation-v3", ["Leagues", "GET", "/leagues", "", { response: [] }], false, ["Football"]),
  api("balldontlie", "balldontlie NBA", "NBA players, teams, games and statistics.", "Sports", "https://api.balldontlie.io/v1", "API key required", "https://docs.balldontlie.io/", ["List teams", "GET", "/teams", "", { data: [] }], false, ["Basketball"]),
  api("nflverse", "nflverse Data", "Open NFL play-by-play and season datasets.", "Sports", "https://github.com/nflverse/nflverse-data/releases/download", "None", "https://nflverse.nflverse.com/", ["Season roster CSV", "GET", "/rosters/roster_2024.csv", "", { format: "CSV" }], true, ["NFL", "Data"]),
  api("f1", "OpenF1", "Formula 1 live timing, sessions and telemetry.", "Sports", "https://api.openf1.org/v1", "None", "https://openf1.org/", ["List sessions", "GET", "/sessions", "year=2024", [{ session_name: "Race" }]], true, ["Motorsport"]),

  // Movies / Entertainment
  api("tvmaze", "TVmaze", "TV show search and schedule data.", "Movies / Entertainment", "https://api.tvmaze.com", "None", "https://www.tvmaze.com/api", ["Search shows", "GET", "/search/shows", "q=the+office", [{ show: { name: "The Office" } }]], true, ["TV"]),
  api("omdb", "OMDb API", "Movie information and ratings.", "Movies / Entertainment", "https://www.omdbapi.com", "API key required", "https://www.omdbapi.com/", ["Find a movie", "GET", "/", "t=Inception", { Title: "Inception", Response: "True" }], false, ["Movies"]),
  api("tmdb", "The Movie Database", "Movies, TV, people and images.", "Movies / Entertainment", "https://api.themoviedb.org/3", "API key or bearer token required", "https://developer.themoviedb.org/docs", ["Popular movies", "GET", "/movie/popular", "", { results: [] }], false, ["Movies"]),
  api("jikan", "Jikan", "Unofficial MyAnimeList API for anime and manga data.", "Movies / Entertainment", "https://api.jikan.moe/v4", "None", "https://docs.api.jikan.moe/", ["Top anime", "GET", "/top/anime", "", { data: [] }], true, ["Anime"]),
  api("rickmorty", "Rick and Morty API", "Characters, locations and episodes from Rick and Morty.", "Movies / Entertainment", "https://rickandmortyapi.com/api", "None", "https://rickandmortyapi.com/documentation", ["List characters", "GET", "/character", "", { info: {}, results: [] }], true, ["TV"]),
  api("spotify", "Spotify Web API", "Music catalog, playlists and user library.", "Movies / Entertainment", "https://api.spotify.com/v1", "OAuth token required", "https://developer.spotify.com/documentation/web-api", ["Search tracks", "GET", "/search", "q=Daft+Punk\ntype=track", { tracks: { items: [] } }], false, ["Music"]),

  // GitHub / Developer
  api("github", "GitHub REST API", "Repositories, users, issues and developer data.", "GitHub / Developer", "https://api.github.com", "Optional token for higher limits", "https://docs.github.com/en/rest", ["Get Octocat", "GET", "/users/octocat", "", { login: "octocat" }], true, ["Developer"]),
  api("gitlab", "GitLab API", "GitLab projects, groups, users and CI data.", "GitHub / Developer", "https://gitlab.com/api/v4", "Optional token for public endpoints", "https://docs.gitlab.com/api/rest/", ["List projects", "GET", "/projects", "per_page=5", [{ id: 1, name: "..." }]], true, ["Developer"]),
  api("npm-registry", "npm Registry", "Package metadata from the npm registry.", "GitHub / Developer", "https://registry.npmjs.org", "None", "https://github.com/npm/registry/blob/main/docs/REGISTRY-API.md", ["React package", "GET", "/react", "", { name: "react", versions: {} }], true, ["Packages"]),
  api("libraries-io", "Libraries.io", "Open-source package and dependency metadata.", "GitHub / Developer", "https://libraries.io/api", "API key required", "https://libraries.io/api", ["Search libraries", "GET", "/search", "q=react", [{ name: "react" }]], false, ["Packages"]),
  api("stackoverflow", "Stack Exchange API", "Questions, answers, users and tags from Stack Exchange.", "GitHub / Developer", "https://api.stackexchange.com/2.3", "None for basic quota", "https://api.stackexchange.com/docs", ["Recent Stack Overflow questions", "GET", "/questions", "site=stackoverflow\npagesize=5", { items: [] }], true, ["Community"]),
  api("huggingface", "Hugging Face Hub API", "Models, datasets and spaces on the Hugging Face Hub.", "GitHub / Developer", "https://huggingface.co/api", "Optional token for public listing", "https://huggingface.co/docs/hub/api", ["List models", "GET", "/models", "limit=5", [{ id: "..." }]], true, ["ML"]),

  // AI
  api("openai", "OpenAI API", "Models, responses and embeddings for AI applications.", "AI", "https://api.openai.com/v1", "API key required", "https://platform.openai.com/docs/api-reference", ["List models", "GET", "/models", "", { data: [] }], false, ["LLM"]),
  api("anthropic", "Anthropic API", "Claude messages and related AI capabilities.", "AI", "https://api.anthropic.com/v1", "API key required", "https://docs.anthropic.com/en/api", ["Create message", "POST", "/messages", "", { id: "msg_...", content: [] }], false, ["LLM"]),
  api("gemini", "Gemini API", "Google Gemini generative AI models.", "AI", "https://generativelanguage.googleapis.com/v1beta", "API key required", "https://ai.google.dev/gemini-api/docs", ["Generate content", "POST", "/models/gemini-2.0-flash:generateContent", "", { candidates: [] }], false, ["LLM"]),
  api("mistral", "Mistral AI API", "Mistral chat completions and embeddings.", "AI", "https://api.mistral.ai/v1", "API key required", "https://docs.mistral.ai/api/", ["Chat completion", "POST", "/chat/completions", "", { choices: [] }], false, ["LLM"]),
  api("cohere", "Cohere API", "Generation, embeddings and reranking.", "AI", "https://api.cohere.com/v2", "API key required", "https://docs.cohere.com/", ["Chat", "POST", "/chat", "", { message: {} }], false, ["LLM"]),
  api("replicate", "Replicate API", "Run and manage hosted machine-learning models.", "AI", "https://api.replicate.com/v1", "API token required", "https://replicate.com/docs/reference/http", ["List models", "GET", "/models", "", { results: [] }], false, ["ML"]),

  // E-commerce
  api("fake-store", "Fake Store API", "Sample products and carts for e-commerce prototypes.", "E-commerce", "https://fakestoreapi.com", "None", "https://fakestoreapi.com/docs", ["Get product", "GET", "/products/1", "", { id: 1, title: "..." }], true, ["Mock"]),
  api("dummyjson-products", "DummyJSON Products", "Product catalog and cart sample data.", "E-commerce", "https://dummyjson.com", "None", "https://dummyjson.com/docs/products", ["List products", "GET", "/products", "limit=5", { products: [] }], true, ["Mock"]),
  api("stripe", "Stripe API", "Payments, customers, invoices and subscriptions.", "E-commerce", "https://api.stripe.com/v1", "Secret key required", "https://docs.stripe.com/api", ["List products", "GET", "/products", "", { data: [] }], false, ["Payments"]),
  api("shopify", "Shopify Admin API", "Store products, orders and customers.", "E-commerce", "https://{shop}.myshopify.com/admin/api/2025-01", "Store access token required", "https://shopify.dev/docs/api/admin-rest", ["List products", "GET", "/products.json", "", { products: [] }], false, ["Store"]),
  api("paypal", "PayPal REST API", "PayPal orders, payments and payouts.", "E-commerce", "https://api-m.sandbox.paypal.com", "OAuth client credentials required", "https://developer.paypal.com/api/rest/", ["Create order", "POST", "/v2/checkout/orders", "", { id: "...", status: "CREATED" }], false, ["Payments"]),
  api("woocommerce", "WooCommerce REST API", "Products, orders and customers for WooCommerce stores.", "E-commerce", "https://example.com/wp-json/wc/v3", "Consumer key and secret required", "https://woocommerce.github.io/woocommerce-rest-api-docs/", ["List products", "GET", "/products", "", []], false, ["Store"]),

  // Education
  api("open-library", "Open Library", "Books, authors and editions from an open catalog.", "Education", "https://openlibrary.org", "None", "https://openlibrary.org/developers/api", ["Search books", "GET", "/search.json", "q=api+design", { docs: [] }], true, ["Books"]),
  api("crossref", "Crossref REST API", "Scholarly works, journals, publishers and DOI metadata.", "Education", "https://api.crossref.org", "None", "https://api.crossref.org/swagger-ui/index.html", ["Search works", "GET", "/works", "query=machine+learning\nrows=5", { message: { items: [] } }], true, ["Research"]),
  api("openalex", "OpenAlex", "Open scholarly works, authors, institutions and concepts.", "Education", "https://api.openalex.org", "None", "https://docs.openalex.org/", ["Search works", "GET", "/works", "search=climate+change\nper-page=5", { results: [] }], true, ["Research"]),
  api("wikipedia", "Wikipedia REST API", "Wikipedia page summaries and content.", "Education", "https://en.wikipedia.org/api/rest_v1", "None", "https://www.mediawiki.org/wiki/API_reference", ["Page summary", "GET", "/page/summary/India", "", { title: "India", extract: "..." }], true, ["Knowledge"]),
  api("gutenberg", "Project Gutenberg", "Public-domain books and metadata.", "Education", "https://gutendex.com", "None", "https://gutendex.com/", ["List books", "GET", "/books", "search=pride", { results: [] }], true, ["Books"]),
  api("datamuse", "Datamuse", "Word-finding, related-word and vocabulary queries.", "Education", "https://api.datamuse.com", "None", "https://www.datamuse.com/api/", ["Related words", "GET", "/words", "ml=happy", [{ word: "glad", score: 0 }]], true, ["Language"]),

  // Government
  api("data-gov", "Data.gov Catalog API", "US government open-data catalog metadata.", "Government", "https://catalog.data.gov/api/3", "None", "https://catalog.data.gov/api/3", ["Package search", "GET", "/action/package_search", "q=climate\nrows=5", { result: { results: [] } }], true, ["Open Data"]),
  api("usa-gov", "USA.gov Search API", "Search USA.gov content and services.", "Government", "https://api.gsa.gov/technology/searchgov/v2", "API key required", "https://search.gov/developer/", ["Search", "GET", "/results.json", "query=benefits", { web: {} }], false, ["US"]),
  api("govuk", "GOV.UK Content API", "Content items and publishing data from GOV.UK.", "Government", "https://www.gov.uk/api", "None", "https://content-api.publishing.service.gov.uk/", ["Search content", "GET", "/search.json", "q=passport", { results: [] }], true, ["UK"]),
  api("fbi", "FBI Crime Data API", "US crime data and summaries.", "Government", "https://cde.ucr.cjis.gov/LATEST", "API key required", "https://cde.ucr.cjis.gov/LATEST/webapp/#/pages/docApi", ["Arrest states", "GET", "/arrest/state", "from=2020\nto=2020\ntype=totals", { data: [] }], false, ["US"]),
  api("nasa", "NASA APIs", "NASA imagery, astronomy and mission data.", "Government", "https://api.nasa.gov", "API key required (DEMO_KEY has strict limits)", "https://api.nasa.gov/", ["Astronomy picture", "GET", "/planetary/apod", "", { title: "...", url: "..." }], false, ["Science"]),
  api("census", "US Census Data API", "US Census demographic and economic datasets.", "Government", "https://api.census.gov/data/2023/acs/acs5", "None for many datasets", "https://www.census.gov/data/developers/data-sets.html", ["Population estimate", "GET", "/profile", "get=NAME,DP05_0001E\nfor=state:*", [["NAME", "DP05_0001E"]]], true, ["US"]),

  // Social
  api("reddit", "Reddit JSON API", "Public subreddit and post listings.", "Social", "https://www.reddit.com", "OAuth required for production usage", "https://www.reddit.com/dev/api/", ["Subreddit hot posts", "GET", "/r/programming/hot.json", "limit=5", { data: { children: [] } }], false, ["Community"]),
  api("mastodon", "Mastodon API", "Federated social-network timelines and accounts.", "Social", "https://mastodon.social/api/v1", "None for public timelines", "https://docs.joinmastodon.org/api/", ["Public timeline", "GET", "/timelines/public", "limit=5", []], true, ["Federated"]),
  api("bluesky", "Bluesky AT Protocol", "Public Bluesky feeds, profiles and social graph.", "Social", "https://public.api.bsky.app/xrpc", "None for public endpoints", "https://docs.bsky.app/docs/api/", ["Get profile", "GET", "/app.bsky.actor.getProfile", "actor=atproto.com", { handle: "atproto.com" }], true, ["Federated"]),
  api("discord", "Discord API", "Discord applications, guilds and channels.", "Social", "https://discord.com/api/v10", "Bot token or OAuth required", "https://discord.com/developers/docs/intro", ["Current user", "GET", "/users/@me", "", { id: "...", username: "..." }], false, ["Community"]),
  api("slack", "Slack Web API", "Slack conversations, users and messaging.", "Social", "https://slack.com/api", "OAuth token required", "https://api.slack.com/web", ["List conversations", "GET", "/conversations.list", "", { ok: true, channels: [] }], false, ["Work"]),
  api("youtube", "YouTube Data API", "YouTube videos, channels, playlists and search.", "Social", "https://www.googleapis.com/youtube/v3", "API key or OAuth required", "https://developers.google.com/youtube/v3", ["Search videos", "GET", "/search", "part=snippet\nq=API", { items: [] }], false, ["Video"]),

  // Random / Data
  api("random-user", "Random User", "Random user profile data for prototypes.", "Random / Data", "https://randomuser.me", "None", "https://randomuser.me/documentation", ["Generate user", "GET", "/api", "", { results: [] }], true, ["Testing"]),
  api("random-data", "Random Data API", "Random names, addresses, users and other sample data.", "Random / Data", "https://random-data-api.com/api", "None", "https://random-data-api.com/documentation", ["Random user", "GET", "/v2/users", "size=1", [{ id: 1, uid: "..." }]], true, ["Testing"]),
  api("random-org", "RANDOM.ORG", "True random values from atmospheric noise.", "Random / Data", "https://www.random.org", "None for HTTP integers endpoint", "https://www.random.org/clients/http/api/", ["Random integers", "GET", "/integers/", "num=5\nmin=1\nmax=10\ncol=1\nbase=10\nformat=plain\nrnd=new", "1\n2\n3"], true, ["Random"]),
  api("numbers", "Numbers API", "Trivia and facts about numbers and dates.", "Random / Data", "http://numbersapi.com", "None", "http://numbersapi.com/", ["Number trivia", "GET", "/42/trivia", "json=true", { text: "42 is ...", number: 42 }], true, ["Fun"]),
  api("universities", "Universities API", "Worldwide university names and domains.", "Random / Data", "http://universities.hipolabs.com", "None", "https://github.com/Hipo/university-domains-list-api", ["Indian universities", "GET", "/search", "country=India", [{ name: "...", domains: [] }]], true, ["Reference"]),
  api("sunrise-sunset", "Sunrise-Sunset", "Sunrise, sunset and civil-twilight times.", "Random / Data", "https://api.sunrise-sunset.org", "None", "https://sunrise-sunset.org/api", ["Sun times", "GET", "/json", "lat=28.6139\nlng=77.2090\nformatted=0", { results: { sunrise: "..." }, status: "OK" }], true, ["Time"])
];

export const categories = ["All", "Testing", "Public", "Weather", "Countries", "Maps / Location", "Finance", "Crypto", "News", "Sports", "Movies / Entertainment", "GitHub / Developer", "AI", "E-commerce", "Education", "Government", "Social", "Random / Data"];
